## Étapes de la pipeline
stages:
  - image_build 
  - deploy

# Variables globales
variables:
  KIND_CLUSTER_NAME: "kind"
  KUBE_NAMESPACE: "dev"
  HELM_RELEASE_NAME: "myapplication"
  IMAGE_TAG: "latest"

# Job pour builder et pousser l'image frontend sur DockerHub
frontend_build_push:
  stage: image_build
  image: docker:20.10.7
  script: 
    - |
      if ! docker info | grep -q "Username: $DOCKERHUB_USERNAME"; then
        echo "Logging into DockerHub..."
        echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      else
        echo "Already logged in as $DOCKERHUB_USERNAME"
      fi
    - echo "Building and pushing frontend image"
    - docker build -t $DOCKERHUB_USERNAME/frontend:$IMAGE_TAG -f ./frontend/Dockerfile .
    - docker push $DOCKERHUB_USERNAME/frontend:$IMAGE_TAG
  tags:
    - build-image  #  Tag of the local gitlab-runner that we use 

# Job pour builder et pousser l'image backend sur DockerHub
backend_build_push:
  stage: image_build
  image: docker:20.10.7
  script:
    - echo "Building and pushing backend image"
    - docker build -t $DOCKERHUB_USERNAME/backend:$IMAGE_TAG -f ./backend/Dockerfile .
    - docker push $DOCKERHUB_USERNAME/backend:$IMAGE_TAG 
  tags:
    - build-image #  Tag of the local gitlab-runner that we use 

# Déployer sur Kubernetes local (Kind)
deploy_app:
  stage: deploy
  image: dtzar/helm-kubectl:3.16.1
  before_script:
    - kubectl config get-contexts
    - kubectl config use-context kind-$KIND_CLUSTER_NAME
    - |
      if ! kubectl get namespace $KUBE_NAMESPACE; then
        kubectl create namespace $KUBE_NAMESPACE
      else
        echo "Namespace $KUBE_NAMESPACE already exists"
      fi
  script:
    - echo "Deploying application with Helm"
    - helm upgrade --install $HELM_RELEASE_NAME ./k8s-helm/ --set front.image.repository=$DOCKERHUB_USERNAME/frontend --set front.image.tag=$IMAGE_TAG --set backend.image.repository=$DOCKERHUB_USERNAME/backend --set backend.image.tag=$IMAGE_TAG --namespace $KUBE_NAMESPACE
  tags:
    - deploy-helm # Tag of the local gitlab-runner that we use 

