apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / 
    kubernetes.io/ingress.class: "nginx"  # it is mandatory to add it because we use nginx-ingress-controller 
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-front-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-backend-service
            port:
              number: 8080
