{{- if .Values.rbac.enabled }} #condition for activation of RBAC
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-backend-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-backend-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-backend-sa
    namespace: {{ .Release.Namespace }} 
{{- end }}

---

{{- if .Values.rbac.enabled }}  #condition for activation of RBAC
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-front-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-front-role
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-front-sa
    namespace: {{ .Release.Namespace }}
{{- end }}