apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-backend-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-front-sa
  namespace: {{ .Release.Namespace }}
