front:
  replicas: 1
  image:
    repository: XXX # the repository is set in the gitlab ci pipeline  
    tag: test # the version of the image that was pushed on the dockerhub it will be set in the gitlab-ci 
  env:
    REACT_APP_BACKEND_URL: "http://myapplication.local.test:30947/api"  # 30947 the Node Port number of the nginx ingress controller service (NodePort) it is mandatory to get it  to call the application wih 


backend:
  replicas: 1
  image:
    repository: XXX  # the repository is set in the gitlab ci pipeline
    tag: test # the version of the image that was pushed on the dockerhub it will be set in the gitlab-ci 
  env:
    SPRING_POSTGRES_USERNAME: "test_username" #it will be changed with real value when we test the application
    SPRING_POSTGRES_PASSWORD: "test_pass" #it will be changed with real value  when we test the application
    SPRING_POSTGRES_URL: "test_db_host"  #it will be changed with real value when we test the application
    

rbac:
  enabled: true  #condition for activation of RBAC



ingress:
  host: "myapplication.local.test"